version: "3.9"
services:
  mongo:
    image: mongo
    expose: ["27017"]
    logging:
      driver: none
  ai:
    build: flaskServer/
    expose: ["5000"]
  api:
    build: backend/
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_DATABASE=retail-marketplace
      - PORT=3001
    links:
      - mongo:mongo
      - ai
    expose: ["3001", "4000"]
    ports:
      - "3001:3001"
  web:
    build: frontend/
    environment:
      - API_HOSTNAME=api
      - API_PORT=3001
      - PUBLIC_API_HOSTNAME=localhost
      - PUBLIC_API_PORT=3001
    links:
      - api:api
    ports:
      - "3000:3000"
